server:
  port: 8181
spring:
  datasource:
    name: test
    url: jdbc:mysql://localhost:3306/node_st
    username: root
    password: 20166332
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  ## 前端UI时区（GMT+8）
  jackson:
    time-zone: Hongkong
    date-format: yyyy-MM-dd HH:mm:ss

